# Generated by Django 5.1.5 on 2025-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
