# Generated by Django 5.1.5 on 2025-02-08 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_compensation_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='compensation',
        ),
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.CharField(default=5, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.contact'),
        ),
        migrations.DeleteModel(
            name='Compensation',
        ),
    ]
