# Generated by Django 5.1.5 on 2025-02-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_employee_compensation_employee_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
