# Generated by Django 5.1.5 on 2025-02-09 09:35

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employee_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.HashIndex(fields=['first_name'], name='hr_employee_first_name_index'),
        ),
    ]
