# Generated by Django 5.1.5 on 2025-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(default=0)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
